# number of threads for multi-threaded applications - overriden by -j option to snakemake
threads: 24

# Directory where the raw reads are stored
read_directory: "demultiplex"


run_name: "ticks"
batches: ["ticks1", "ticks2", "ticks3" ]
#batches: ["ticks1"]
samples: ['1', '2', '3']

metacategory: ['Species']
sampling-depth: '10000'
perc-identity: 99

#alpha
rarefaction-min-depth: 1
rarefaction-max-depth: 20000
rarefaction-steps: 20
rarefaction-iterations: 10

#beta
rarefaction-metric: "unweighted_unifrac"
correlation-method: "spearman"
