# number of threads for multi-threaded applications - overriden by -j option to snakemake
num_threads: 4

# Directory where the raw reads are stored
read_directory: "fastq_raw"

# Directory where the rRNA databases are stored
db_directory: "rRNA_databases"

# Unique sample descriptors - should be in the file names
samples: ["1", "2"]

dbfiles: ["rfam-5.8s-database-id98.fasta", "rfam-5s-database-id98.fasta", "silva-arc-16s-id95.fasta", "silva-arc-23s-id98.fasta", "silva-bac-16s-id90.fasta", "silva-bac-23s-id98.fasta", "silva-euk-18s-id95.fasta", "silva-euk-28s-id98.fasta"]

run_name: "vole"
